name: Audit Action Demo
on: [push]
#on:
#  push:
#    branches:    
#      - 'main'
#    paths:
#      - '**.sol'
jobs:
  Audit-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install -y software-properties-common
      - run: sudo add-apt-repository ppa:ethereum/ethereum
      - run: sudo apt install -y solc
      - run: sudo apt install -y libssl-dev python3-dev python3-pip
      - run: yes | pip3 install mythril
      - run: myth version
      - run: myth analyze *.sol
      #- run: ls -R

